"""refactor flight plan and aircraft fields to normativa format

Revision ID: 05bbc20fb20c
Revises: c3d4e5f6a1b2
Create Date: 2026-06-18 04:48:35.361674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05bbc20fb20c'
down_revision: Union[str, None] = 'c3d4e5f6a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('emergency_radio_uhf', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('emergency_radio_vhf', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('emergency_radio_elt', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('survival_equipment_present', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('survival_polar', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('survival_desert', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('survival_maritime', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('survival_jungle', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('life_jackets_present', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('life_jackets_lights', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('life_jackets_fluorescein', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('life_jackets_uhf', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('life_jackets_vhf', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('dinghies_present', sa.Boolean(), nullable=False))
    op.add_column('aircraft', sa.Column('dinghies_cover_present', sa.Boolean(), nullable=False))
    op.drop_column('aircraft', 'survival_equipment')
    op.drop_column('aircraft', 'emergency_radio')
    op.drop_column('aircraft', 'life_jackets')
    op.drop_column('aircraft', 'dinghies_cover')
    op.alter_column('controlled_aerodromes', 'traffic_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('controlled_aerodromes', 'flight_rules',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('controlled_aerodromes', 'category',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.add_column('flight_plans', sa.Column('aircraft_number', sa.Integer(), nullable=False))
    op.add_column('flight_plans', sa.Column('departure_time_utc', sa.String(length=4), nullable=True))
    op.add_column('flight_plans', sa.Column('flight_date', sa.Date(), nullable=True))
    op.add_column('flight_plans', sa.Column('emergency_radio_uhf_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('emergency_radio_vhf_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('emergency_radio_elt_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('survival_equipment_present_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('survival_polar_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('survival_desert_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('survival_maritime_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('survival_jungle_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('life_jackets_present_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('life_jackets_lights_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('life_jackets_fluorescein_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('life_jackets_uhf_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('life_jackets_vhf_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('dinghies_present_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('dinghies_cover_present_snapshot', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('remarks_present', sa.Boolean(), nullable=False))
    op.add_column('flight_plans', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('flight_plans', sa.Column('pilot_in_command', sa.String(length=255), nullable=True))
    op.add_column('flight_plans', sa.Column('signature_url', sa.String(length=512), nullable=True))
    op.drop_column('flight_plans', 'survival_equipment_snapshot')
    op.drop_column('flight_plans', 'departure_eobt_utc')
    op.drop_column('flight_plans', 'dinghies_cover_snapshot')
    op.drop_column('flight_plans', 'emergency_radio_snapshot')
    op.drop_column('flight_plans', 'rule_change_point')
    op.drop_column('flight_plans', 'life_jackets_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_plans', sa.Column('life_jackets_snapshot', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('flight_plans', sa.Column('rule_change_point', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('flight_plans', sa.Column('emergency_radio_snapshot', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('flight_plans', sa.Column('dinghies_cover_snapshot', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('flight_plans', sa.Column('departure_eobt_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('flight_plans', sa.Column('survival_equipment_snapshot', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('flight_plans', 'signature_url')
    op.drop_column('flight_plans', 'pilot_in_command')
    op.drop_column('flight_plans', 'remarks')
    op.drop_column('flight_plans', 'remarks_present')
    op.drop_column('flight_plans', 'dinghies_cover_present_snapshot')
    op.drop_column('flight_plans', 'dinghies_present_snapshot')
    op.drop_column('flight_plans', 'life_jackets_vhf_snapshot')
    op.drop_column('flight_plans', 'life_jackets_uhf_snapshot')
    op.drop_column('flight_plans', 'life_jackets_fluorescein_snapshot')
    op.drop_column('flight_plans', 'life_jackets_lights_snapshot')
    op.drop_column('flight_plans', 'life_jackets_present_snapshot')
    op.drop_column('flight_plans', 'survival_jungle_snapshot')
    op.drop_column('flight_plans', 'survival_maritime_snapshot')
    op.drop_column('flight_plans', 'survival_desert_snapshot')
    op.drop_column('flight_plans', 'survival_polar_snapshot')
    op.drop_column('flight_plans', 'survival_equipment_present_snapshot')
    op.drop_column('flight_plans', 'emergency_radio_elt_snapshot')
    op.drop_column('flight_plans', 'emergency_radio_vhf_snapshot')
    op.drop_column('flight_plans', 'emergency_radio_uhf_snapshot')
    op.drop_column('flight_plans', 'flight_date')
    op.drop_column('flight_plans', 'departure_time_utc')
    op.drop_column('flight_plans', 'aircraft_number')
    op.alter_column('controlled_aerodromes', 'category',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('controlled_aerodromes', 'flight_rules',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('controlled_aerodromes', 'traffic_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.add_column('aircraft', sa.Column('dinghies_cover', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('life_jackets', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('emergency_radio', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('survival_equipment', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('aircraft', 'dinghies_cover_present')
    op.drop_column('aircraft', 'dinghies_present')
    op.drop_column('aircraft', 'life_jackets_vhf')
    op.drop_column('aircraft', 'life_jackets_uhf')
    op.drop_column('aircraft', 'life_jackets_fluorescein')
    op.drop_column('aircraft', 'life_jackets_lights')
    op.drop_column('aircraft', 'life_jackets_present')
    op.drop_column('aircraft', 'survival_jungle')
    op.drop_column('aircraft', 'survival_maritime')
    op.drop_column('aircraft', 'survival_desert')
    op.drop_column('aircraft', 'survival_polar')
    op.drop_column('aircraft', 'survival_equipment_present')
    op.drop_column('aircraft', 'emergency_radio_elt')
    op.drop_column('aircraft', 'emergency_radio_vhf')
    op.drop_column('aircraft', 'emergency_radio_uhf')
    # ### end Alembic commands ###
