"""add flight plan tables

Revision ID: 1f415d96c495
Revises: c51de2d7e5e7
Create Date: 2026-05-19 17:34:09.432925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1f415d96c495'
down_revision: Union[str, None] = 'c51de2d7e5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport_operator_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_name', sa.String(length=160), nullable=False),
    sa.Column('aerodrome_icao_code', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airport_operator_profiles_aerodrome_icao_code'), 'airport_operator_profiles', ['aerodrome_icao_code'], unique=False)
    op.create_index(op.f('ix_airport_operator_profiles_user_id'), 'airport_operator_profiles', ['user_id'], unique=True)
    op.create_table('authority_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_name', sa.String(length=160), nullable=False),
    sa.Column('authority_type', sa.Enum('ARO', 'AIS', 'ACC', 'APP', 'TWR', 'EANA', 'ANAC', name='authoritytype'), nullable=False),
    sa.Column('aerodrome_icao_code', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authority_profiles_aerodrome_icao_code'), 'authority_profiles', ['aerodrome_icao_code'], unique=False)
    op.create_index(op.f('ix_authority_profiles_user_id'), 'authority_profiles', ['user_id'], unique=True)
    op.create_table('pilot_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('license_number', sa.String(length=80), nullable=False),
    sa.Column('license_type', sa.String(length=40), nullable=False),
    sa.Column('license_country', sa.String(length=2), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilot_profiles_user_id'), 'pilot_profiles', ['user_id'], unique=True)
    op.create_table('flight_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pilot_user_id', sa.Uuid(), nullable=False),
    sa.Column('aircraft_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'filed', 'pending_approval', 'accepted', 'rejected', 'active', 'closed', 'cancelled', name='flightplanstatus'), nullable=False),
    sa.Column('flight_rules', sa.Enum('V', 'I', 'Y', 'Z', name='flightrules'), nullable=True),
    sa.Column('flight_type', sa.Enum('G', 'S', 'N', 'M', 'X', name='flighttype'), nullable=True),
    sa.Column('departure_aerodrome_icao', sa.String(length=4), nullable=False),
    sa.Column('departure_eobt_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destination_aerodrome_icao', sa.String(length=4), nullable=False),
    sa.Column('alternate1_aerodrome_icao', sa.String(length=4), nullable=False),
    sa.Column('alternate2_aerodrome_icao', sa.String(length=4), nullable=False),
    sa.Column('cruising_speed', sa.String(length=5), nullable=True),
    sa.Column('cruising_level', sa.String(length=5), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('rule_change_point', sa.String(length=40), nullable=True),
    sa.Column('total_eet', sa.String(length=4), nullable=True),
    sa.Column('other_information', sa.Text(), nullable=True),
    sa.Column('endurance', sa.String(length=4), nullable=True),
    sa.Column('persons_on_board', sa.Integer(), nullable=True),
    sa.Column('aircraft_identification_snapshot', sa.String(length=20), nullable=True),
    sa.Column('aircraft_type_designator_snapshot', sa.String(length=10), nullable=True),
    sa.Column('wake_turbulence_category_snapshot', postgresql.ENUM('L', 'M', 'H', 'J', name='waketurbulencecat', create_type=False), nullable=True),
    sa.Column('equipment_com_nav_snapshot', sa.String(length=80), nullable=True),
    sa.Column('equipment_surveillance_snapshot', sa.String(length=80), nullable=True),
    sa.Column('emergency_radio_snapshot', sa.String(length=20), nullable=True),
    sa.Column('survival_equipment_snapshot', sa.String(length=20), nullable=True),
    sa.Column('life_jackets_snapshot', sa.String(length=20), nullable=True),
    sa.Column('dinghies_number_snapshot', sa.Integer(), nullable=True),
    sa.Column('dinghies_capacity_snapshot', sa.Integer(), nullable=True),
    sa.Column('dinghies_cover_snapshot', sa.Boolean(), nullable=True),
    sa.Column('dinghies_color_snapshot', sa.String(length=40), nullable=True),
    sa.Column('color_and_markings_snapshot', sa.String(length=255), nullable=True),
    sa.Column('aircraft_snapshot_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.ForeignKeyConstraint(['pilot_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_plans_aircraft_id'), 'flight_plans', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_flight_plans_departure_aerodrome_icao'), 'flight_plans', ['departure_aerodrome_icao'], unique=False)
    op.create_index(op.f('ix_flight_plans_destination_aerodrome_icao'), 'flight_plans', ['destination_aerodrome_icao'], unique=False)
    op.create_index(op.f('ix_flight_plans_pilot_user_id'), 'flight_plans', ['pilot_user_id'], unique=False)
    op.create_index(op.f('ix_flight_plans_status'), 'flight_plans', ['status'], unique=False)
    op.create_table('flight_plan_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flight_plan_id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.Enum('pilot', 'authority', 'destination_aerodrome_operator', name='flightplanapprovalactor'), nullable=False),
    sa.Column('criterion', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='flightplanapprovalstatus'), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('rejected_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['flight_plan_id'], ['flight_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_plan_approvals_actor'), 'flight_plan_approvals', ['actor'], unique=False)
    op.create_index(op.f('ix_flight_plan_approvals_flight_plan_id'), 'flight_plan_approvals', ['flight_plan_id'], unique=False)
    op.create_index(op.f('ix_flight_plan_approvals_status'), 'flight_plan_approvals', ['status'], unique=False)
    op.create_table('flight_plan_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flight_plan_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('draft', 'filed', 'pending_approval', 'accepted', 'rejected', 'active', 'closed', 'cancelled', name='flightplanstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('draft', 'filed', 'pending_approval', 'accepted', 'rejected', 'active', 'closed', 'cancelled', name='flightplanstatus'), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flight_plan_id'], ['flight_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_plan_status_history_flight_plan_id'), 'flight_plan_status_history', ['flight_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_plan_status_history_flight_plan_id'), table_name='flight_plan_status_history')
    op.drop_table('flight_plan_status_history')
    op.drop_index(op.f('ix_flight_plan_approvals_status'), table_name='flight_plan_approvals')
    op.drop_index(op.f('ix_flight_plan_approvals_flight_plan_id'), table_name='flight_plan_approvals')
    op.drop_index(op.f('ix_flight_plan_approvals_actor'), table_name='flight_plan_approvals')
    op.drop_table('flight_plan_approvals')
    op.drop_index(op.f('ix_flight_plans_status'), table_name='flight_plans')
    op.drop_index(op.f('ix_flight_plans_pilot_user_id'), table_name='flight_plans')
    op.drop_index(op.f('ix_flight_plans_destination_aerodrome_icao'), table_name='flight_plans')
    op.drop_index(op.f('ix_flight_plans_departure_aerodrome_icao'), table_name='flight_plans')
    op.drop_index(op.f('ix_flight_plans_aircraft_id'), table_name='flight_plans')
    op.drop_table('flight_plans')
    op.drop_index(op.f('ix_pilot_profiles_user_id'), table_name='pilot_profiles')
    op.drop_table('pilot_profiles')
    op.drop_index(op.f('ix_authority_profiles_user_id'), table_name='authority_profiles')
    op.drop_index(op.f('ix_authority_profiles_aerodrome_icao_code'), table_name='authority_profiles')
    op.drop_table('authority_profiles')
    op.drop_index(op.f('ix_airport_operator_profiles_user_id'), table_name='airport_operator_profiles')
    op.drop_index(op.f('ix_airport_operator_profiles_aerodrome_icao_code'), table_name='airport_operator_profiles')
    op.drop_table('airport_operator_profiles')
    # ### end Alembic commands ###
