"""add validation criteria table

Revision ID: 8f830384e363
Revises: 05bbc20fb20c
Create Date: 2026-06-19 16:37:10.637584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f830384e363'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('field_path', sa.String(length=200), nullable=False),
    sa.Column('operator', sa.Enum('eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'contains', 'not_contains', 'is_present', 'is_absent', name='criterionoperator'), nullable=False),
    sa.Column('expected_value', sa.String(length=200), nullable=True),
    sa.Column('result_on_pass', sa.Enum('approve', 'warn', 'reject', name='criterionresult'), nullable=False),
    sa.Column('result_on_fail', sa.Enum('approve', 'warn', 'reject', name='criterionresult'), nullable=False),
    sa.Column('pass_message', sa.Text(), nullable=True),
    sa.Column('fail_message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_criteria_created_by_user_id'), 'validation_criteria', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_validation_criteria_is_active'), 'validation_criteria', ['is_active'], unique=False)
    op.drop_column('flight_plans', 'official_pdf_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_plans', sa.Column('official_pdf_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_validation_criteria_is_active'), table_name='validation_criteria')
    op.drop_index(op.f('ix_validation_criteria_created_by_user_id'), table_name='validation_criteria')
    op.drop_table('validation_criteria')
    # ### end Alembic commands ###
