"""add image_url to aircraft

Revision ID: c51de2d7e5e7
Revises: 357a662aee93
Create Date: 2026-05-13 06:39:58.665036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51de2d7e5e7'
down_revision: Union[str, None] = '357a662aee93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('image_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aircraft', 'image_url')
    # ### end Alembic commands ###
