#!/usr/bin/env python3
"""Generate a sample filled EANA PDF for local visual calibration."""

from __future__ import annotations

import base64
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.pdf.eana_flight_plan_data import EanaFlightPlanPdfData  # noqa: E402
from app.pdf.eana_flight_plan_pdf_generator import EanaFlightPlanPdfGenerator  # noqa: E402

SAMPLE_DATA_PATH = ROOT / "scripts" / "eana_pdf_sample_data.json"
OUTPUT_PATH = ROOT / "tmp" / "eana_sample_filled.pdf"
DEFAULT_SIGNATURE_PATH = ROOT / "docs" / "signature-example.png"

# 1x1 transparent PNG fallback when no sample signature file is available
TINY_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+X2ZkAAAAASUVORK5CYII="
)


def load_sample_signature_png() -> bytes:
    if DEFAULT_SIGNATURE_PATH.exists():
        return DEFAULT_SIGNATURE_PATH.read_bytes()
    return TINY_PNG


def main() -> None:
    if SAMPLE_DATA_PATH.exists():
        raw = json.loads(SAMPLE_DATA_PATH.read_text(encoding="utf-8"))
        signature_b64 = raw.pop("signature_png_base64", None)
        data = EanaFlightPlanPdfData(
            text_fields=raw.get("text_fields", {}),
            mark_fields=raw.get("mark_fields", {}),
            signature_png_bytes=base64.b64decode(signature_b64) if signature_b64 else load_sample_signature_png(),
        )
    else:
        data = EanaFlightPlanPdfData(
            text_fields={
                "aircraft_identification_snapshot": "LVABCDE",
                "departure_aerodrome_icao": "SABE",
                "departure_time_utc": "1430",
                "destination_aerodrome_icao": "SAEZ",
                "pilot_in_command": "Amelia Earhart Amelia Earhart Amelia Earhart Amelia Earhart Amelia Earhart",
                "aircraft_number": "01",
                "aircraft_type_designator_snapshot": "C172",
                "wake_turbulence_category_snapshot": "C",
                "equipment_com_nav_snapshot": "ADE3RV/HB2U2V2G1",
                "cruising_speed": "N01200",
                "cruising_level": "FL100",
                "route": "DCT GUALE DCT SANTU DCT ARROYO DCT PAL VFR DCT GUALE DCT SANTU DCT ARROYO DCT PAL VFR DCT GUALE DCT SANTU DCT ARROYO DCT PAL VFR DCT GUALE DCT SANTU DCT ARROYO DCT PAL VFR DCT GUALE DCT SANTU DCT ARROYO DCT PAL VFR DCT GUALE DCT SANTU DCT ARROYO DCT PAL VFR DCT GUALE DCT SANTU DCT ARROYO DCT PAL VFR DCT GUALE DCT SANTU DCT ARROYO DCT PAL VFR DCT GUALE DCT SANTU DCT ARROYO DCT PAL VFR DCT GUALE DCT SANTU DCT ARROYO DCT PAL VFR",
                "total_eet": "0120",
                "alternate1_aerodrome_icao": "SAEZ",
                "alternate2_aerodrome_icao": "SAEZ",
                "other_information": "OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA OTF OTF PBN/C1 DDDAAA",
                "endurance": "0120",
                "persons_on_board": "30",
                "flight_rules": "V",
                "flight_type": "G",
                "dinghies_number": "01",
                "dinghies_capacity": "0111",
                "dinghies_color": "RED RED RED RED RED RED",
                "color_and_markings_snapshot": " RED WITH YELLOW STRIPES RED WITH YELLOW STRIPES RED WITH YELLOW STRIPES RED WITH YELLOW STRIPES",
                "remarks": "REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS REMARKS"
            },
            mark_fields={
                "emergency_radio_uhf": True,
                "emergency_radio_vhf": True,
                "emergency_radio_elt": True,
                "survival_equipment_present": True,
                "survival_polar": True,
                "survival_desert": True,
                "survival_maritime": True, 
                "survival_jungle": True,
                "life_jackets_present": True,
                "life_jackets_lights": True,
                "life_jackets_fluorescein": True,
                "life_jackets_uhf": True,
                "life_jackets_vhf": True,
                "dinghies_present": True,
                "dinghies_cover_present": True,
                "remarks_present": True,
            },
            signature_png_bytes=load_sample_signature_png(),
        )

    generator = EanaFlightPlanPdfGenerator()
    pdf_bytes = generator.generate(data)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_bytes(pdf_bytes)
    print(f"Wrote sample PDF to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
