FPL_FIELD_MAP: dict[str, dict] = {
    "aircraft_identification_snapshot":         {"item": 7,  "label": "Identificación de aeronave"},
    "flight_rules":                             {"item": 8,  "label": "Reglas de vuelo"},
    "flight_type":                              {"item": 8,  "label": "Tipo de vuelo"},
    "aircraft_number":                          {"item": 9,  "label": "Número de aeronaves"},
    "aircraft_type_designator_snapshot":        {"item": 9,  "label": "Tipo de aeronave"},
    "wake_turbulence_category_snapshot":        {"item": 9,  "label": "Estela turbulenta"},
    "equipment_com_nav_snapshot":               {"item": 10, "label": "Equipo COM/NAV"},
    "equipment_surveillance_snapshot":          {"item": 10, "label": "Equipo vigilancia"},
    "departure_aerodrome_icao":                 {"item": 13, "label": "Aeródromo de salida"},
    "departure_time_utc":                       {"item": 13, "label": "EOBT (HHMM UTC)"},
    "cruising_speed":                           {"item": 15, "label": "Velocidad de crucero"},
    "cruising_level":                           {"item": 15, "label": "Nivel de crucero"},
    "route":                                    {"item": 15, "label": "Ruta"},
    "total_eet":                                {"item": 16, "label": "EET total"},
    "destination_aerodrome_icao":               {"item": 16, "label": "Aeródromo de destino"},
    "alternate1_aerodrome_icao":                {"item": 16, "label": "Alternativo 1"},
    "alternate2_aerodrome_icao":                {"item": 16, "label": "Alternativo 2"},
    "other_information":                        {"item": 18, "label": "Otros datos (Casilla 18)"},
    "remarks_present":                          {"item": 18, "label": "Observaciones (N/)"},
    "remarks":                                  {"item": 18, "label": "Texto observaciones"},
    "endurance":                                {"item": 19, "label": "Autonomía"},
    "persons_on_board":                         {"item": 19, "label": "Personas a bordo"},
    "emergency_radio_uhf_snapshot":             {"item": 19, "label": "Radio UHF"},
    "emergency_radio_vhf_snapshot":             {"item": 19, "label": "Radio VHF"},
    "emergency_radio_elt_snapshot":             {"item": 19, "label": "Radio ELT"},
    "survival_equipment_present_snapshot":      {"item": 19, "label": "Equipo supervivencia (S)"},
    "survival_polar_snapshot":                  {"item": 19, "label": "Supervivencia Polar"},
    "survival_desert_snapshot":                 {"item": 19, "label": "Supervivencia Desierto"},
    "survival_maritime_snapshot":               {"item": 19, "label": "Supervivencia Marítimo"},
    "survival_jungle_snapshot":                 {"item": 19, "label": "Supervivencia Jungla"},
    "life_jackets_present_snapshot":            {"item": 19, "label": "Chalecos salvavidas"},
    "life_jackets_lights_snapshot":             {"item": 19, "label": "Chalecos - Luces"},
    "life_jackets_fluorescein_snapshot":        {"item": 19, "label": "Chalecos - Fluoresceína"},
    "life_jackets_uhf_snapshot":                {"item": 19, "label": "Chalecos - UHF"},
    "life_jackets_vhf_snapshot":                {"item": 19, "label": "Chalecos - VHF"},
    "dinghies_present_snapshot":                {"item": 19, "label": "Botes (D)"},
    "dinghies_number_snapshot":                 {"item": 19, "label": "Número de botes"},
    "dinghies_capacity_snapshot":               {"item": 19, "label": "Capacidad de botes"},
    "dinghies_cover_present_snapshot":          {"item": 19, "label": "Botes cubiertos (C)"},
    "dinghies_color_snapshot":                  {"item": 19, "label": "Color de botes"},
    "color_and_markings_snapshot":              {"item": 19, "label": "Color y marcas"},
    "pilot_in_command":                         {"item": 19, "label": "Piloto al mando"},
}
