FPL_FIELD_MAP: dict[str, dict] = {
    "aircraft_identification_snapshot":   {"item": 7,  "label": "Identificación de aeronave"},
    "flight_rules":                       {"item": 8,  "label": "Reglas de vuelo"},
    "flight_type":                        {"item": 8,  "label": "Tipo de vuelo"},
    "aircraft_type_designator_snapshot":  {"item": 9,  "label": "Tipo de aeronave"},
    "wake_turbulence_category_snapshot":  {"item": 9,  "label": "Estela turbulenta"},
    "number_of_aircraft":                 {"item": 9,  "label": "Número de aeronaves"},
    "equipment_com_nav_snapshot":         {"item": 10, "label": "Equipo COM/NAV"},
    "equipment_surveillance_snapshot":    {"item": 10, "label": "Equipo vigilancia"},
    "departure_aerodrome_icao":           {"item": 13, "label": "Aeródromo de salida"},
    "departure_eobt_utc":                 {"item": 13, "label": "EOBT (UTC)"},
    "cruising_speed":                     {"item": 15, "label": "Velocidad de crucero"},
    "cruising_level":                     {"item": 15, "label": "Nivel de crucero"},
    "route":                              {"item": 15, "label": "Ruta"},
    "rule_change_point":                  {"item": 15, "label": "Punto de cambio de reglas"},
    "total_eet":                          {"item": 16, "label": "EET total"},
    "destination_aerodrome_icao":         {"item": 16, "label": "Aeródromo de destino"},
    "alternate1_aerodrome_icao":          {"item": 16, "label": "Alternativo 1"},
    "alternate2_aerodrome_icao":          {"item": 16, "label": "Alternativo 2"},
    "other_information":                  {"item": 18, "label": "Otros datos"},
    "endurance":                          {"item": 19, "label": "Autonomía"},
    "persons_on_board":                   {"item": 19, "label": "Personas a bordo"},
    "emergency_radio_snapshot":           {"item": 19, "label": "Radio de emergencia"},
    "survival_equipment_snapshot":        {"item": 19, "label": "Equipo de supervivencia"},
    "life_jackets_snapshot":              {"item": 19, "label": "Chalecos salvavidas"},
    "dinghies_number_snapshot":           {"item": 19, "label": "Número de botes"},
    "dinghies_capacity_snapshot":         {"item": 19, "label": "Capacidad de botes"},
    "dinghies_cover_snapshot":            {"item": 19, "label": "Botes cubiertos"},
    "dinghies_color_snapshot":            {"item": 19, "label": "Color de botes"},
    "color_and_markings_snapshot":        {"item": 19, "label": "Color y marcas"},
    "pilot_user_id":                      {"item": 19, "label": "Piloto al mando"},
}
